import type { WorldCommand } from "../world";

/**
 * What the scripted AI can do, by command and by building: who issues it, or why nobody does. A table, so a new
 * command or building type fails the type check (commands) or the coverage test (buildings) until someone says
 * how the AI uses it. `tests/aicoverage.test.ts` checks that each claimed owner's source really mentions the
 * command or building; whether the order is ever *given* in play is measured by `npm run soak -- coverage`.
 */
export type Owner = { by: string } | { exempt: string };

const by = (file: string): Owner => ({ by: file });
const exempt = (why: string): Owner => ({ exempt: why });

export const COMMAND_OWNERS: Record<WorldCommand["t"], Owner> = {
  flag: by("econ/planner.ts"),
  road: by("econ/planner.ts"),
  build: by("econ/planner.ts"),
  demolish: by("ai/builder.ts"),
  geologist: by("ai/economy.ts"),
  prio: by("ai/economy.ts"),
  toolprio: by("ai/builder.ts"),
  transport: by("ai/economy.ts"),
  storeMode: by("ai/economy.ts"),
  storeGood: by("ai/economy.ts"),
  explore: by("ai/sea.ts"),
  ferry: exempt("a foothold quay is built with its ferry (the build command makes the link); no other pairing is wanted"),
  unferry: exempt("the scripted AI never closes a ferry link; a learned policy could"),
  upgrade: by("ai/sea.ts"),
  rotate: by("ai/economy.ts"),
  garrison: by("ai/builder.ts"),
  attack: by("ai/builder.ts"),
  hedge: by("ai/economy.ts"),
  causeway: by("ai/economy.ts"),
  palisade: by("ai/war.ts"),
  camp: by("ai/war.ts"),
  bridge: by("ai/works.ts"),
  raid: by("ai/war.ts"),
  propose: by("ai/builder.ts"),
  answer: exempt("an AI seat answers every offer at once through the world's answer hook (answerOffer), so no offer is ever left for a command"),
  break: by("ai/war.ts"),
  send: by("ai/works.ts"),
  probe: by("ai/voyage.ts"),
  hearthship: by("ai/voyage.ts"),
  land: by("ai/voyage.ts"),
  route: by("ai/voyage.ts"),
  unroute: by("ai/voyage.ts"),
  steward: exempt("seat management (a person leaving or returning), not a move in the game"),
};

/** Buildings by the planner that places them. */
export const BUILDING_OWNERS: Record<string, Owner> = {
  keep: exempt("the Hearthship is placed at the start, never built"),
  house: by("ai/builder.ts"),
  treehouse: by("ai/biome.ts"),
  storehouse: by("ai/economy.ts"),
  launchrail: by("ai/voyage.ts"),
  mirrorworks: by("ai/terra.ts"),
  greenhouseworks: by("ai/terra.ts"),
  cometcatcher: by("ai/terra.ts"),
  cloudseeder: by("ai/terra.ts"),
  lakebasin: by("ai/terra.ts"),
  seedhouse: by("ai/terra.ts"),
  genebank: by("ai/terra.ts"),
  reserve: by("ai/terra.ts"),
  digsite: by("ai/works.ts"),
  maypole: by("ai/works.ts"),
  flowerbed: by("ai/builder.ts"),
  bench: by("ai/builder.ts"),
  fountain: by("ai/works.ts"),
  statue: by("ai/works.ts"),
  well: by("ai/builder.ts"),
  waystation: by("ai/biome.ts"),
  woodcutter: by("ai/builder.ts"),
  forester: by("ai/builder.ts"),
  quarry: by("ai/builder.ts"),
  sawmill: by("ai/builder.ts"),
  saltworks: by("ai/biome.ts"),
  solarkiln: by("ai/biome.ts"),
  peatcutter: by("ai/biome.ts"),
  ropeway: by("ai/biome.ts"),
  farm: by("ai/builder.ts"),
  mill: by("ai/builder.ts"),
  tidemill: by("ai/biome.ts"),
  bakery: by("ai/builder.ts"),
  fisher: by("ai/builder.ts"),
  hunter: by("ai/builder.ts"),
  orchard: by("ai/builder.ts"),
  apiary: by("ai/builder.ts"),
  greenhouse: by("ai/biome.ts"),
  dewcondenser: by("ai/biome.ts"),
  shellfisher: by("ai/biome.ts"),
  glowcapfarm: by("ai/biome.ts"),
  pasture: by("ai/builder.ts"),
  butcher: by("ai/builder.ts"),
  coalmine: by("ai/economy.ts"),
  ironmine: by("ai/economy.ts"),
  goldmine: by("ai/economy.ts"),
  granitemine: by("ai/economy.ts"),
  smelter: by("ai/economy.ts"),
  goldsmith: by("ai/economy.ts"),
  toolsmith: by("ai/builder.ts"),
  lantern: by("ai/builder.ts"),
  lamphouse: by("ai/builder.ts"),
  beacon: by("ai/builder.ts"),
  lighthouse: by("ai/biome.ts"),
  quay: by("ai/sea.ts"),
  harbour: exempt("made by upgrading a quay (the upgrade command), never placed"),
  boatyard: by("ai/sea.ts"),
  weaponsmith: by("ai/builder.ts"),
  bowyer: by("ai/economy.ts"),
  stable: by("ai/economy.ts"),
};
